version: '3'

services:
  # Database
  mydb:
    image: mysql:5.7
    volumes:
      - mydb_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: faisal
      MYSQL_PASSWORD: faisal
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mydb
    image: phpmyadmin
    restart: always
    ports:
      - '8000:80'
    environment:
      PMA_HOST: mydb
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - mydb
    image: wordpress:latest
    ports:
      - '8001:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: mydb:3306
      WORDPRESS_DB_USER: faisal
      WORDPRESS_DB_PASSWORD: faisal
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  mydb_data:
